# Generated by Django 5.0.8 on 2025-02-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_payment_status_payment_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_status',
            new_name='status',
        ),
    ]
