# Generated by Django 5.0.8 on 2025-02-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_booking_guest_email_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
