# Generated by Django 5.0.8 on 2025-02-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest_email',
        ),
    ]
