# Generated by Django 5.0.8 on 2025-02-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_booking_guest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
