# Generated by Django 5.0.8 on 2025-02-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_payment_email_address_payment_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
